Repository eggjs/egg-core, pull requests merged in 2023-01, with the labels that each got.

#236 feat: use globby@11
  package.json
Labels: enhancement, egg3

#257 fix: @types/depd and @types/koa should be dependencies
  package.json
Labels: bug

#260 feat: support show app.timing in timline string
  lib/utils/timing.js
  package.json
  test/egg.test.js
  test/utils/timing.test.js
Labels: enhancement
